### PR TITLE
Text are not being affected when an object is outside bounds (#1904)

### PR DESCRIPTION
**Pull request by QThund**
## What does this PR change?

Now TextMeshPro labels are hidden when they leave their scenes.

## How to test the changes?

There are several scenarios that can be tested:

### **1 -------------------------------------**
It is easier to test in Unity editor although.

1. Launch the explorer
2. Enable the Show scene bounds option in the Debug panel.
3. Move the avatar to the boundaries of the Genesis plaza.
4. Drag an object that has a text label, like the jukebox, near to the boundaries.
5. Slowly drag the object outside of the scene.

The label should hide when it is outside, and show when it enters again.

### **2 -------------------------------------**
1. Copy the provided script into a local scene.
2. Wait for the label to touch the boundaries and move back.

https://github.com/user-attachments/assets/242c9e26-a691-4f47-b200-a733e72ddef9

```
export function main() {
    const entity = engine.addEntity()
    Transform.create(entity, { position: Vector3.create(0, 0, 0) })

    TextShape.create(entity)
    const mutableText = TextShape.getMutable(entity);
    mutableText.text = "XXXX"

    Tween.create(entity, {
        mode: Tween.Mode.Move({
          start: Vector3.create(3, 1, 7),
          end: Vector3.create(10, 1, 8),
        }),
        duration: 4000,
        easingFunction: EasingFunction.EF_LINEAR,
      })
      
      TweenSequence.create(entity, { sequence: [], loop: TweenLoop.TL_YOYO })
}
```

### **3 -------------------------------------**
1. Copy the provided script into a local scene.
2. Click on the text. It adds another character to the text. Repeat until it touches the boundaries of the scene.
3. Click more times until it resets to 1 character.

In step 2, the text should hide. In the step 3, it should show again.

https://github.com/user-attachments/assets/5163519f-cfd3-40ee-b8c4-63858a96e90e

```
export function main() {
    const entity = engine.addEntity()
    Transform.create(entity, { position: Vector3.create(0, 0, 0) })

    TextShape.create(entity)
    const mutableText = TextShape.getMutable(entity);
    mutableText.text = "XXXX"

    MeshCollider.setBox(entity);

    //AvatarAttach.create(entity, { anchorPointId: AvatarAnchorPointType.AAPT_LEFT_LEG});
    pointerEventsSystem.onPointerDown(
      {
      entity: entity,
      opts: {
          button: InputAction.IA_POINTER,
          hoverText: 'Click'
        }
      },
      function () {
        
        const t = TextShape.getMutable(entity)

        if(t.text.length > 10)
        {
          console.log("Text changed, width reset")
          t.text = "X";
        }
        else
        {
          console.log("Text changed, width increased")
          t.text += "X"
        }
      }
        )
}
```

### CODE REVIEW

**Review by pravusjif — APPROVED** [review]

**Review by m3taphysics — APPROVED** [review]
Nice and simple solution!

**Comment by QThund** [comment]
> Nice and simple solution!

It's going to change after talking with Alvaro and Juani.

**Comment by QThund** [comment]
It can be reviewed and tested now.

**Review by anicalbano — APPROVED** [review]
🟢 Tested on editor mode scene and working as expected. The object used was the jukebox on Goerli plaza located on (73,-5)

**Pull request merged**
