### PR TITLE
fix: Music of Genesis Plaza keeps playing on the log in screen

### LINKED ISSUE #1355: [QA] Music of Genesis Plaza keeps playing on the log in screen
### **Explorer Alpha build version:**
v0.10.0

### **Issue Description:**

After being on Genesis Plaza and logging out (not exit) the music of Genesis can be heard overlapping the log in music.

### **Steps to reproduce:**

  1. Log in and stay in Genesis Plaza
  2. Log out and return to the log in screen
  3. Log in again

### **Expected behavior:**
Only the music of the login can be heard when the world is loading

### **Current behaviour:**
The music is overlapping

#### **Evidence:**

https://github.com/decentraland/unity-explorer/assets/139157886/79e669d3-1904-4385-b4ff-623f4baa7949

### PR DESCRIPTION
**Pull request by sandrade-dcl**
## What does this PR change?
Fix #1355 

## How to test the changes?
1. Log in and stay in Genesis Plaza.
2. Log out and return to the log in screen.
3. Check that Genesis Plaza music is off while the log in scren is open.

## Our Code Review Standards
https://github.com/decentraland/unity-renderer/blob/master/docs/code-review-standards.md

### CODE REVIEW

**Comment by anicalbano** [comment]
🔴 I can still hear the music after logging out:

https://github.com/decentraland/unity-explorer/assets/139157886/d34ace2c-327a-4e0f-b484-62a899b7e718

**Comment by sandrade-dcl** [comment]
> 🔴 I can still hear the music after logging out:

Hmmm... I'm seeing that the reason why it's not working, is because the changes in the volume of the "**World SFX**" channel are not working in the build (it works from editor), I don't know why...

In fact, if you go to the settings menu and try to change the "World SFX" slider, you will see that the the volume of the background music in Genesis Plaza doesn't change:

image

@anicalbano This is effectively a different issue. I'm not sure if we should create a different ticket for that or try to fix it directly in this one. In any case I'm gonna investigate why is it happening.

**Comment by sandrade-dcl** [comment]
@anicalbano issue created: https://github.com/decentraland/unity-explorer/issues/1395

**Comment by anicalbano** [comment]
> @anicalbano after talking with Ash, we decided to create a new issue for this: #1395
> 
> In my opinion we should merge this fix (although it doesn't still work because it depends on the other issue) and leave the responsibility to the other issue.

Agreed, then let's merge this and check with the fix of #1395 , thanks, Santi!

**Review by anicalbano — APPROVED** [review]
🟢 QA approved

**Pull request merged**
