### PR TITLE
Fix: terrain color blend rerender

### LINKED ISSUE #748: [QA] Terrain blending stops working after coming back from a world.
If you telepor to a world, and then go back to genesis city, the terrain blending stops working

image

### LINKED ISSUE #756: loading screen does not wait for terrain to finish generation
1. Jump to a world (or goerli plaza)
2. Notice the water is visible and terrain is generated in the background while its running

### PR DESCRIPTION
**Pull request by popuz**
## What does this PR change?
fix #748
fix #756

## How to test the changes?

1. Launch the explorer
2. Go to some world -> verify world terrain already presented after loading screen disappears
3. go back to genesis city -> verify grass in not red (see #748)
4. try this loop several times (but with jumping between stable worlds and empty genesis terrain)
5. check how it works at night
6. verify that  building at -150,-3 is not covered by bushes (it is owned parcel). Like that 

## Our Code Review Standards

https://github.com/decentraland/unity-renderer/blob/master/docs/code-review-standards.md

### CODE REVIEW

**Comment by olavra** [comment]
The grass still looks extremely Red

image

**Comment by olavra** [comment]
Talk to @Kinerius. We had this issue where noise texture generation was giving odd red values out of range.

**Comment by Kinerius** [comment]
> Talk to @Kinerius. We had this issue where noise texture generation was giving odd red values out of range.

Noise is not a texture and it never gave odd red values.

The issue is the plugin that we use for the terrain blending, is bugged as hell and we have to do some workarounds to properly make it work during runtime

**Comment by popuz** [comment]
> > Talk to @Kinerius. We had this issue where noise texture generation was giving odd red values out of range.
> 
> Noise is not a texture and it never gave odd red values.
> 
> The issue is the plugin that we use for the terrain blending, is bugged as hell and we have to do some workarounds to properly make it work during runtime

Agree. But as for this bug, it was directly related to culling.

**Review by Kinerius — APPROVED** [review]
LGTM

**Pull request merged**
