### PR TITLE
fix: upgrade arch to the latest commit

### PR DESCRIPTION
**Pull request by m3taphysics**
## What does this PR change?

It is an alternative fix for:

https://github.com/decentraland/unity-explorer/issues/1193
https://github.com/decentraland/unity-explorer/issues/1181

## How to test the changes?

Verify the two bugs above.

## Our Code Review Standards

https://github.com/decentraland/unity-renderer/blob/master/docs/code-review-standards.md

### CODE REVIEW

**Comment by anicalbano** [comment]
- The issues can still be reproduced with the build. 
- The spawn point is 147,60 instead of Genesis Plaza

**Comment by LucasLioyQA** [comment]
There are still issues on the build. After teleporting for some time, loading issues start taking place. Check this video in Genesis for example: 

https://github.com/decentraland/unity-explorer/assets/146749313/60be5d0e-8db2-4068-8135-d9c87e0e6a52

These are the logs: 

[logs scenes not loading well.log](https://github.com/user-attachments/files/15973674/logs.scenes.not.loading.well.log)

**Comment by m3taphysics** [comment]
After discussions with @popuz we decided that this issue is unrelated to the original issue, so we can tackle this separately.

**Review by popuz — APPROVED** [review]
In editor issue with `IndexOutOfRange `for Arch is fixed

**Pull request merged**
