### PR TITLE
chore: sdk camera control minor iteration

### PR DESCRIPTION
**Pull request by pravusjif**
Updated protocol and adapted to it.

Related PRs:
* https://github.com/decentraland/protocol/pull/219
* https://github.com/decentraland/js-sdk-toolchain/pull/998
* https://github.com/decentraland/sdk7-test-scenes/pull/17

## Summary by CodeRabbit

- **New Features**
	- Enhanced camera transition handling with structured management for different modes (Time, Speed).
	- Improved clarity on virtual camera entity presence checks.

- **Bug Fixes**
	- Streamlined `CameraTransition` class by removing unused fields, focusing on essential properties.

- **Documentation**
	- Updated comments to clarify behavior and usage of camera transition and virtual camera entity features.

- **Chores**
	- Changed dependency versioning method for `@dcl/protocol` to a fixed reference URL.

----------------------------------------------------

## QA TEST INSTRUCTIONS

* Download this PR's Explorer build
* Access the `pravus.dcl.eth` world for running the test scene (`/goto pravus`)
* Once the scene loads you are ready to test 
    * Pressing 'E' will cycle between the scene virtual cameras
    * When you are with the Character default camera, if you look up you will be able to see the 4 entities that have virtual cameras (represented as cubes). The numbers represent the order in which they will be cycled.

Things to test:
### Using the Character default camera
1.  Enter the Avatar Modifier Area and exit it (being in third person cam), confirm that the Avatar is hidden only when inside the area.
2. Being in Third Person Cam enter the Camera Mode Area and confirm that the camera is forcefully changed to 1st perdon cam. Check that you can't change the camera mode inside that area but that it resets when you get out of it.

### Using the SDK Camera 1
1. Confirm that you can move normally as you would if you were in third person cam.
2. Enter the Avatar Modifier Area and exit it, confirm that the Avatar is hidden only when inside the area.
3. Enter the Camera Mode Area and confirm that it doesn't change the camera at all.

### Using the SDK Camera 2
1. Confirm that you can move normally as you would if you were in third person cam.
2. Enter the Avatar Modifier Area and exit it, confirm that the Avatar is hidden only when inside the area.
3. Enter the Camera Mode Area and confirm that it doesn't change the camera at all.
4. Exit the scene, and confirm that the camera goes back to the Character default camera and you can still control it. Then re-enter the scene and check that the last SDK Camera that was active is now active again.

### Using the SDK Camera 3
1. Confirm that this camera **constantly looks at the player**, even when you move the player.
2. Confirm that you can move normally as you would if you were in third person cam.
3. Enter the Avatar Modifier Area and exit it, confirm that the Avatar is hidden only when inside the area.
4. Enter the Camera Mode Area and confirm that it doesn't change the camera at all.
5. Exit the scene, and confirm that the camera goes back to the Character default camera and you can still control it. Then re-enter the scene and check that the last SDK Camera that was active is now active again.

### Using the SDK Camera 4
1. Confirm that you can move normally as you would if you were in third person cam.
2. Enter the Avatar Modifier Area and exit it, confirm that the Avatar is hidden only when inside the area.
3. Enter the Camera Mode Area and confirm that it doesn't change the camera at all.
4. Exit the scene, and confirm that the camera goes back to the Character default camera and you can still control it. Then re-enter the scene and check that the last SDK Camera that was active is now active again.

### Camera Mode Area
1. Being in character's default camera
-> move inside the CameraModeArea that will force 1st person cam 
-> press 'E' to activate any SDK camera (doesn't matter which one) 
-> cycle through the cameras until you get back to the character camera 
-> confirm that you are again under the effect of the Camera Mode Area 
-> get out of the Camera Mode Area and confirm you can control the camera again
2. Being in character's default camera 
-> press 'E' to activate any SDK camera (doesn't matter which one) 
-> move the character inside the CameraModeArea 
-> cycle through the cameras until you get back to the character camera 
-> confirm that you are now under the effect of the Camera Mode Area 
-> get out of the Camera Mode Area and confirm you can control the camera again
3. Being in character's default camera 
-> move inside the CameraModeArea that will force 1st person cam 
-> press 'E' to activate any SDK camera (doesn't matter which one) 
-> move the character outside the Camera Mode Area 
-> cycle through the cameras until you get back to the character camera 
-> confirm that you free from the effect of the Camera Mode Area and you can control the camera again
4. Being in character's default camera 
-> move inside the CameraModeArea that will force 1st person cam 
-> press 'E' to activate any SDK camera (doesn't matter which one) 
-> move the character outside the Camera Mode Area 
-> move the character inside the Camera Mode Area again 
-> cycle through the cameras until you get back to the character camera 
-> confirm that you are still under the effect of the Camera Mode Area 
-> get out of the Camera Mode Area and confirm you can control the camera again
5. Being in character's default camera 
-> press 'E' to activate any SDK camera (doesn't matter which one) 
-> move the character inside the Camera Mode Area 
-> move the character outside the Camera Mode Area again 
-> cycle through the cameras until you get back to the character camera 
-> confirm that you are still free from the effect of the Camera Mode Area

### Video reference for testing
https://github.com/user-attachments/assets/9da43c6d-120c-4571-935a-dcc2e76c5e0a

### CODE REVIEW

**Comment by pravusjif** [comment]
TODO: after protocol PR gets merged, update the package used by this branch

**Review by AlejandroAlvarezMelucciDCL — APPROVED** [review]
LGTM, I like that you took good care of the case with no mode set on the SDK, something we learned recently with the Input Modifier 😅 Good job 💪

**Review by popuz — APPROVED** [review]
LGTM!

**Review by dalkia — APPROVED** [review]

**Review by anicalbano — APPROVED** [review]
🟢 Reviewed by QA and working as expected, as per the instructions on the PR

https://github.com/user-attachments/assets/04aa38c4-e7ed-435b-9a18-8a7a51deced0


https://github.com/user-attachments/assets/061c7701-6a01-459f-9d45-f68d816d81d6


Uploading 20.09.2024_08.34.26_REC.mp4…

**Pull request merged**
